CREATE DATABASE GYM
USE GYM

--CREACION DE TABLAS
--------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE CLIENTES(
    ID INT NOT NULL,
    NOMBRE VARCHAR(15),
    APELLIDO VARCHAR(20),
    CEDULA VARCHAR(10),
    SEXO VARCHAR(10),
    F_NACIMIENTO date,
    PRIMARY KEY(ID)
)


CREATE TABLE SUCURSALES(
    ID_SUCURSAL INT NOT NULL,
    NOMBRE_SUCURSAL VARCHAR(30),
    UBICACION VARCHAR(30) UNIQUE,
    PRIMARY KEY(ID_SUCURSAL)
)


CREATE TABLE PLANES(
    ID VARCHAR(15) NOT NULL,
    NOMBRE VARCHAR(15),
    COD_SUCURSAL INT,
    COSTO DECIMAL,
    DESCRIPCION VARCHAR(30),
    PRIMARY KEY(ID),
    FOREIGN KEY (COD_SUCURSAL) REFERENCES SUCURSALES(ID_SUCURSAL)
)


CREATE TABLE INSCRIPCIONES(
    NRO_INSCRIPCION INT NOT NULL UNIQUE,
    FECHA_INSCRIPCION DATE,
    ID_CLIENTE INT,
    PLAN_ID VARCHAR(15),
    INICIO DATE,
    FIN DATE,
    DEUDA DECIMAL,
    DESCRIPCION VARCHAR(40),
    PRIMARY KEY(NRO_INSCRIPCION),
    FOREIGN KEY (PLAN_ID) REFERENCES PLANES(ID),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
)


CREATE TABLE PAGO(
    COD_INSCRIPCION INT,
    FECHA DATE,
    SALDO DECIMAL,
    DETALLES VARCHAR(30),
    FOREIGN KEY (COD_INSCRIPCION) REFERENCES INSCRIPCIONES(NRO_INSCRIPCION)
)


CREATE TABLE REDES(
    ID_REDES INT,
    WHATSAPP VARCHAR(25),
    FACEBOOK VARCHAR(30),
    INSTAGRAM VARCHAR(30),
    CORREO VARCHAR(40),
    PRIMARY KEY(ID_REDES)
)


CREATE TABLE INFO_CONTACTO(
    ID_CLIENTE INT,
    TELEFONO VARCHAR(15),
    TEL_FAMILIAR VARCHAR(15),
    DIRECCION VARCHAR(40),
    ID_SOCIAL INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
    FOREIGN KEY (ID_SOCIAL) REFERENCES REDES(ID_REDES),
)


CREATE TABLE HISTORIAL(
    ID INT NOT NULL,
    FECHA DATE,
    FOREIGN KEY(ID) REFERENCES CLIENTES(ID)
)


CREATE TABLE PERFILES(
    ID_PERFIL INT NOT NULL,
    ID_CLIENTE INT,
    ESTATURA VARCHAR(10),
    PESO_INICIAL VARCHAR(10),
    PESO_ACTUAL VARCHAR(10),
    PRIMARY KEY(ID_PERFIL),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
)


CREATE TABLE LESIONES(
    ID_PER INT NOT NULL,
    POSEE_LESIONES VARCHAR(5),
    NOMBRE_LESION VARCHAR(20),
    FOREIGN KEY (ID_PER) REFERENCES PERFILES(ID_PERFIL)
)


CREATE TABLE LESIONADOS(
    ID_PERF INT NOT NULL,
    NOMBRE_LESION VARCHAR(20),
    DIA DATE,
    DESCRIPCION VARCHAR(50),
    FOREIGN KEY (ID_PERF) REFERENCES PERFILES(ID_PERFIL)
)


CREATE TABLE USUARIOS(
    NOMBRE VARCHAR(30) NOT NULL,
    PASS VARCHAR(50) NOT NULL UNIQUE,
    CORREO VARCHAR(80) NOT NULL UNIQUE,
)
